### ISSUE TITLE
People even not realize how is cool this project.

### ISSUE THREAD

**Issue by anacondaq** [srounet/Pymem#1]
Thank you dear developer for your awesome work. You make my life much easier with this module.

**Comment by srounet** [comment]
Thank you, I appreciate a lot your feedback!

**Comment by anacondaqq** [comment]
btw, do you have any simple examples?) Can you share them:)

For example very simple & stupid application to read process memory & automaticly press keys while memory value at address X1 < then memory value at address X2

**Comment by srounet** [comment]
For examples on how to use the library you can have a look at this post:
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/524785-release-python-pymem-python-memory-library.html#post3309988

Basically it opens "world of warcraft" process, reads memory, write assembly, loads directx module.

Documentation is also available here: http://pymem.readthedocs.org/

**Comment by anacondaqq** [comment]
You make a very hard things very simple. Thank you. I will try.

**Comment by omarbgm** [comment]
is there is anyway to use pymem to make it clicking few buttons ?
