### ISSUE TITLE
x64 branch development overtaking master / x86

### ISSUE THREAD

**Issue by MattAlp** [srounet/Pymem#11]
Will the x64 branch ever be merged onto master? It seems to be considerably more active and fleshed out, and would be extremely beneficial for users running on x64 machines who don't want to rely on FASM.

**Comment by srounet** [comment]
I've just merged x64 into master and released pymem as `1.0` onto pypi.

Thank you for taking the time to start an issue for this, it always makes me react and motivates to push the project forward.

**Comment by MattAlp** [comment]
Thank you for putting in the time to make this and keeping it alive!
