### ISSUE TITLE
I updated from 0.3 to 1.0 and everything broke, any documentation of changes?

### ISSUE THREAD

**Issue by jimmycorkhill** [srounet/Pymem#14]
I left a message on Discord too. 

I just need to figure out what changed and what I need to change in the code.

**Comment by srounet** [comment]
sadly not, we have a discord channel where you can discuss issues too, most of the interface has changed and all the write/reads from memory has been tested and are fully working now.

Still 0.3 to 1.0 is a huge step forward, I would adive you come to discord :)

**Comment by srounet** [comment]
I'm closing this issue, new comers should install 1.0.0 directly, nobody should be using 0.3 in 2020.
