### ISSUE TITLE
Cannot write or read bytes: buffer type is void

### ISSUE THREAD

**Issue by Apprisco** [srounet/Pymem#146]
According to the docs, the buffer type for the write_bytes function is Void.
There is no example anywhere online on how to write bytes to a specific address.

**Comment by StarrFox** [comment]
that looks to be a typo in the documentation, the correct type is `bytes` 

it's correctly marked on Pymem.write_bytes https://pymem.readthedocs.io/en/latest/api.html?highlight=write_bytes#pymem.Pymem.write_bytes

also sorry about the late response
