### ISSUE TITLE
process_base_address

### ISSUE THREAD

**Issue by wu294499348** [srounet/Pymem#15]
Can't find process_base_address API,

How to get the base address,
TypeError: Address must be int: <pymem.ressources.structure.MODULEINFO object at 0x000002D9DAA16B48>

Unable to open

**Comment by srounet** [comment]
I would suggest you come over discord so you can talk with the community and give more details about your issue.
It could be because of 64bits vs 32bits, not running with privileges and other specific issues

**Comment by srounet** [comment]
closing because it s outdated by now.
