### ISSUE TITLE
Understanding 

### ISSUE THREAD

**Issue by omarbgm** [srounet/Pymem#16]
is there is a recomonded knowledge to be able to use adn understand how to work with pymem ?

**Comment by srounet** [comment]
There is no walkthrough. You can either have a look to the code or join the Discord channel, thé community is nice and friendly, depending on your knowledge someone may be able to help you.

**Comment by omarbgm** [comment]
Well thanks but i mean is there is any knowledge necessered to be able to
understand how to use it ?

**Comment by srounet** [comment]
It won’t break your system by any means,  but you definitely need to know basics of reverse engineering. If you don’t i suggest you to read « gray hat python » or books that talks about hacking into windows programs.

**Comment by omarbgm** [comment]
Thats exactly what i was looking for thanks for your help and for ur fast
reply
