### ISSUE TITLE
Help/Suggestions for MapleStory

### ISSUE THREAD

**Issue by linkin69** [srounet/Pymem#17]
Is it possible to use Pymem to inject this ASM script into MapleStory

//v153.1 Bypassless Character Movement Hook 
[ENABLE] 
alloc(Hook, 1024) 
globalalloc(HookRet, 4) 
label(Return) 
label(ReturnHook) 
Hook: 
cmp dword ptr [esp], 01416491 
jne Return 
mov dword ptr [esp], ReturnHook 
Return: jmp dword ptr [HookRet] ReturnHook: 
mov [esp+1C], 0 //Up = #-1 or FFFFFFFF, Down = 1, Nothing = 0 
mov [esp+20], FFFFFFFF //Left = #-1 or FFFFFFFF, Right = 1, Nothing = 0
jmp 01416930 
HookRet: 
readmem(01B77ED0, 4) 
01B77ED0: 
dd Hook

Just an example of a script. Is it possible?

**Comment by srounet** [comment]
In it's current form, pymem does not compile asm anymore.
In the previous version pymem *was* able to compile asm (x86) and then inject the codecave into process memory.

(example here: https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/524785-release-python-pymem-python-memory-library.html)

I would say that if you assemble it somehow, you can then read the assembled bytes and write them into memory.

If I had to do that in the current stage of pymem, I would externally call a process that assemble the asm for me then read it and inject it into process.

**Comment by srounet** [comment]
closing because it s outdated by now.
