### ISSUE TITLE
UnicodeDecodeError raised on process_from_name

### ISSUE THREAD

**Issue by rishubil** [srounet/Pymem#18]
I'm using this library in my project called [TrickyTowersUtils](https://github.com/rishubil/TrickyTowersUtils).
Just before, some user of my project reported the following error message:

```
Traceback (most recent call last):
  File "observer.py", line 100, in <module>
  File "site-packages\pymem__init.py", line 45, in init
  File "site-packages\pymem__init.py", line 194, in open_process_from_name
  File "site-packages\pymem\process.py", line 243, in process_from_name
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 0: invalid continuation byte
```

Perhaps an error occurred while decoding the user's process name.

**Comment by srounet** [comment]
Yeah, looking at the code it points towards:

```
for process in processes:
    if name in process.szExeFile.decode('utf-8').lower():
        return process
```

It depends on the version of Python you are using then, **is it Python3** ?
I'm testing pymem only against:

- python *3.5 X86*
- python *3.5 X64*
- python *3.6 X86*
- python *3.6 X64*

**Comment by rishubil** [comment]
I am using Python 3.7 as defined in the project's Pipfile.
The user who reported the error used an x64 binary created with pyinstaller.

Since most users use the same x64 binaries but the same problem has never been reported, I think this is an issue that only occurs in certain environments.

The user who reported this issue said that the problem was with a "public" computer, not his or her own computer, and did not accurately describe the environment in which the problem occurred.

So, unfortunately, I don't currently have detailed information about the environment in which the problem occurred.
I can only guess that bytes of `szExeFile` can use encodings other than utf-8 in certain environments.

Maybe we'll have to wait for the same error again to get more information.

**Comment by srounet** [comment]
Alright, let s wait for more context.
I ll let this open so google can eventually index this more easily and point other users to it.

**Comment by srounet** [comment]
closing because it s outdated by now.
