### ISSUE TITLE
argument 1: <class 'OverflowError'>: int too long to convert

### ISSUE THREAD

**Issue by kivdev** [srounet/Pymem#19]
Python 3.7.2
Pymem==1.0
Windows 7 error
Windows 10 no error
![J4wLHbJBnMs](https://user-images.githubusercontent.com/45893258/73963224-f4057180-4920-11ea-8088-e7c7e9349879.jpg)

**Comment by srounet** [comment]
Hi @kivdev thank you for reporting this issue, I've never heard of it before. seems like it's `check_wow64` related.
If you're not already on pymem's discord, I suggest you to come over, someone may already had the issue or could come up with a solution.

Unfortunately It's hard to say anything about this issue without more context.

 https://discord.gg/xaWNac8

**Comment by WEGFan** [comment]
I added `pymem_object.process_handle &= 0xffffffff` after open process and it worked, don't know why

**Comment by DyXel** [comment]
Any solution for this problem? im experiencing this with a script i made, works fine on Windows 10, doesn't work on Windows 7.

**Comment by WEGFan** [comment]
> 
> 
> Any solution for this problem? im experiencing this with a script i made, works fine on Windows 10, doesn't work on Windows 7.

try this:
```python
p = pymem.Pymem()
p.open_process_from_name("program.exe")
p.process_handle &= 0xffffffff # this line
```

**Comment by srounet** [comment]
I'm closing the issue as nobody reported anything similar for a year. Feel free to create a new issue if the probleme still occurs with `pymem==1.8`
