### ISSUE TITLE
delete pls

### ISSUE THREAD

**Issue by SomaBots** [srounet/Pymem#2]
Nevermind sir, please delete.

**Comment by srounet** [comment]
> Nevermind sir, please delete. 
Alright :+1: 

I also advice you to use x64 branch of this projet, it's not the main release  (it requrires more testing and cleanup + compatibility) but I used it for a Guildwars2 bot and it was stable.

**Comment by SomaBots** [comment]
Thanks bud. Great project either way. I've got it working now I think. Do you know of a forum or chat group for bot creators?

**Comment by srounet** [comment]
windows structures:
http://terminus.rewolf.pl/terminus/

Forums:
elitepvpers.com
ownedcore.com
blizzhackers.cc
