### ISSUE TITLE
Problem to undertand Pymem

### ISSUE THREAD

**Issue by Dega98** [srounet/Pymem#24]
Good Morning, and sorry for my eng.. i've tryed to understand how works this library, i've use it for make a game trainer, but if a try to write a variable i receive a error "windows api". The function write_int want a adress integer, with cheat engine, my adress is like a 1DBA7D66C30, how works this method?...
i've tryed to get the PID whit the constructor of the class Pymem, my PID is 7252,
so i've get the handle whit the function open() but when i try to get adress whit the function base_module() i receive a None Object.

Someone can tell me how works this library? TY

**Comment by srounet** [comment]
Regarding this questions it's suggested to come to the discord channel and try your chance.
It has nothing to do with pymem it's pure reverse engineering knowledge at this point.

So, I invite you to join the discord and ask your question there.
