### ISSUE TITLE
pymem.Pattern missing from documentation

### ISSUE THREAD

**Issue by StarrFox** [srounet/Pymem#25]
Hello! I noticed that [pymem.Pattern](https://github.com/srounet/Pymem/blob/master/pymem/pattern.py) was missing from the documentation but is still documented in the source code, was this a mistake?

**Comment by srounet** [comment]
The documentation is totally outdated. I know i need to work on it but I don’t had time since 1.0.

**Comment by srounet** [comment]
thank you for your contribution: https://pymem.readthedocs.io/en/latest/api.html#module-pymem.pattern
