### ISSUE TITLE
Another "argument 1: <class 'OverflowError'>: int too long to convert"

### ISSUE THREAD

**Issue by oskros** [srounet/Pymem#38]
I am running a tkinter application that has a check every 100ms for which processes are open. After one of my users had the application open for a long time, suddenly this error occurred in the "process.list_processes()" method in pymem, for this line

`217:    p32 = pymem.ressources.kernel32.Process32First(hSnap, ctypes.byref(process_entry)) `

![95544629-0e24b180-09d2-11eb-8cc7-6b110cd7607f](https://user-images.githubusercontent.com/53574923/95552352-dc7d0c00-0a0c-11eb-944e-893191bbcc1d.png)

**Comment by srounet** [comment]
Is it still the case ? I think we talked a while about that, is it solved, and do you remember what was required to solve it?

**Comment by oskros** [comment]
I found a way to solve it on my side, but I still think theres something going on in pymem

**Comment by srounet** [comment]
Alright, i ll let the issue open, when I have time i ll write a loop that call the method and see how it goes after some time.

**Comment by srounet** [comment]
I m closing it since there is no additional feedback since december
