### ISSUE TITLE
API new function demands

### ISSUE THREAD

**Issue by nblog** [srounet/Pymem#39]
want to add  "read_pointer" and "write_pointer"  and "read_uint64"

"read_string" & "write_string"  
maybe there should be "xxxx_ansi_string"   "xxxx_utf16_string"  "xxxx_utf8_string" 

if you don't mind, hope to have a similar with "[AOBScan](https://wiki.cheatengine.org/index.php?title=Auto_Assembler:aobScan)" function. 

thank you very much
hope you have a good time  🍺

**Comment by srounet** [comment]
I'm closing the issue as @oiramario suggested it's just namings, the basic reading method are already present within pymem.
As for reading strings, if something more elaborate is required feel free to describe that in a separate issue.
Thank you for your suggestions.
