### ISSUE TITLE
How can I combine a list of several offsets?

### ISSUE THREAD

**Issue by jimmycorkhill** [srounet/Pymem#4]
I can't seem to find out the method of combining offsets with an address to get the desired value.

If these are my offsets 	scanshopinventorynameoffset = [0x0, 0x30, 0x0]

shopinventory[i][0] = pm.read_int(0x0536258+ scanshopinventoryidoffset)

I'm guessing I'm doing this completely wrong.

Could you please just clear this up for me? It is taking longer than I expected to get this right.

**Comment by jimmycorkhill** [comment]
I've also tried stuff like this

		shopinventory[i][1] = pm.read_string(0x0536258 + scanshopinventorynameoffset[0] + scanshopinventorynameoffset[1] + scanshopinventorynameoffset[2])

**Comment by srounet** [comment]
How did you get the offsets: `0x0`, `0x3`, `0x0` ?

You could try:

```python
static_pointer_value = pm.read_int(0x0536258)
shopinventory_value = pm.read_string(
  pm.read_int(static_pointer_value + 0x30)
)
```

This may not work, but it depends on how you collected those offsets at first.

**Comment by jimmycorkhill** [comment]
These are offsets for items in a shop inventory http://imgur.com/a/5lZiq

I'll give it a shot. 1 moment.

**Comment by jimmycorkhill** [comment]
That gives me b'\x92\x01' 

The first offset (0x0) it for each item in the shop's inventory. So += 4 is the next item, and I loop through them.

**Comment by jimmycorkhill** [comment]
Ok, I finally figured it out but it feels a bit long winded, is this intentional?

This gives me the desired value from those offsets. I didn't include the last 0 offset.

		static_pointer_value = pm.read_int(0x0536258)
		shopinventory_value = pm.read_int(static_pointer_value + 0x0)
		shopinventory_value = pm.read_string(pm.read_int(shopinventory_value + 0x30))

b'Small Heal Potion'

Is this how I'm supposed to deal with multiple offsets?

**Comment by srounet** [comment]
You can write your own wrapper function around pymem that deals with multiple reads for you:

```python
def read_ints(pm, base, offsets):
    value =  pm.read_int(base)
    for offset in offsets:
        value = pm.read_int(base + offset)
    return value

shopinventory_value = pm.read_string(
  read_ints(pm, 0x0536258, [0x0, 0x30])
)
```

**Comment by jimmycorkhill** [comment]
Thanks for your help, I've been coding bots for many years now using tons of different tools but this is the first time I've used Python. It is incredibly fast and cool to use. Your library is great too. Thanks.

Perhaps in the readme you should add an example on how to use multiple offsets for people like me who are self taught and can get confused easily.

**Comment by srounet** [comment]
You can also have a look to the [RemotePointer](https://github.com/srounet/Pymem/blob/x64/pymem/ptypes.py) class in the [x64](https://github.com/srounet/Pymem/tree/x64) branch which implements `__add__` and let you do things like:

```python
pointer = RemotePointer(process_handle, 0x0536258)
value = pointer + 0x0
```

I'm not at home so I can't give you an interesting snippet right now but in the x64 branch I'm using it a lot in my tests.
