### ISSUE TITLE
mbi.BaseAddress is incorrect

### ISSUE THREAD

**Issue by sanzenwin** [srounet/Pymem#45]
**Describe the bug**

Traceback: scan_pattern_page -> pymem.ressources.kernel32.VirtualQueryEx
In my case,  mbi.BaseAddress should be '0x78c30000', but it show me the '0x78c3000078c30000'

**Your Environment**

1. python version (3.7.2)
2. os version (64)
3. pymem version(1.7)

**Comment by oiramario** [comment]
maybe that's the difference between 32-bits and 64-bits.

**Comment by srounet** [comment]
Could you provide an environment where I can reproduce this issue ?

> python version (3.7.2) > I assume it is 64 bits (as your os suggest)
Can you reproduce it with any system default installed apps (notepad, calc...), which would help in reproducing the issue.

**Comment by srounet** [comment]
@oiramario could you try pymem 1.8.2 and report if the issue still occurs ?

**Comment by StarrFox** [comment]
closing since there has been no response and this is likely fixed
