### ISSUE TITLE
`scan_pattern_page` not finding all matches?

### ISSUE THREAD

**Issue by jmctune** [srounet/Pymem#68]
# **Describe the bug**
Unsure if this is a bug or intended, but I am executing `scan_pattern_page` with a specific byte pattern and getting mixed results back. Here's an example of the code I'm running:

```
import pymem

indexPattern = bytes.fromhex("49 4E 44 58 10 00 00 00")

def process_scan(handle: int, pattern: bytes, end_address: int = 0x7fffffff):
  next_region = 0
  while next_region < end_address:
    next_region, found = pymem.pattern.scan_pattern_page(handle, next_region, pattern)
    if found:
      print(hex(found))

  return found

pm = pymem.Pymem('DQXGame.exe')
handle = pm.process_handle

process_scan(handle, indexPattern)
```

This returns 19 results every time, but I'm expecting 110~ results from this query. 

Output:

```
0x306f79b0
0x313721f0
...
0x48ab50b0
0x49696da0
```

Searching for the same in Cheat Engine:

![image](https://user-images.githubusercontent.com/17505625/127949992-959b6907-760a-4680-a961-f5214075f6a7.png)

# **Your Environment**

- Python Version: `3.9.5`
- OS Version: `64-bit` (working with 32-bit process)
- PyMem Version: `1.8.4`

# **Expected behavior**
Expecting to have every matching pattern of "49 4E 44 58 10 00 00 00", but am getting less than 20% of the results back.

# **Traceback**
N/A

# **Additional context**
N/A

Thanks for any help you can provide.

**Comment by StarrFox** [comment]
This is intended behavior, `scan_pattern_page` only returns the first result it finds.

There is a pr to allow returning multiple results here: https://github.com/srounet/Pymem/pull/59

**Comment by srounet** [comment]
I have just released pymem (1.8.5) with the changes proposed by @StarrFox.
@jmctune could you get the last pymem release and tell us if everything is going the way you need it ?

**Comment by jmctune** [comment]
Hey @srounet - the new changes are working great. Thanks!

**Comment by srounet** [comment]
Nice, you can thanks @StarrFox he made it happen.
