### ISSUE TITLE
Vectors support

### ISSUE THREAD

**Issue by MaGicSuR** [srounet/Pymem#71]
Hi, just wanted to suggest to add support for writing and reading a Vectors (2/3) and that's a 1 thing I sadly missing.

**Comment by MaGicSuR** [comment]
Hey @qb-0 thank you for your contribution. I also have a question if you ever tried to write whole structure with Pymem. How could I achieve that?

**Comment by qb-0** [comment]
Guess something like that could work
```python
import ctypes
import struct
from pymem.memory import write_bytes

class MyStructure(ctypes.Structure):
    _fields_ = [
        ("field1_float", ctypes.c_float),
        ("field2_int", ctypes.c_int32),
    ]

newStruct = MyStructure(1.0, 2, 1)
value = bytearray(newStruct)
length = ctypes.sizeof(newStruct)
res = write_bytes(handle, address, value, length)
```
