### ISSUE TITLE
Can you please help me with this error?

### ISSUE THREAD

**Issue by GDman1616** [srounet/Pymem#8]
Hey I am just trying to learn pymem by looking at some projects and I saw this no-flash cheat for CS:GO it seemed like a good training tried it (of course csgo is in -insecure mode). But I keep getting this error when I run it..
-----------------------------
CODE: https://gist.github.com/GDman1616/f3179ef6fcfa564697dbc149585e8b13

Error: C:\Python27\python.exe C:/Users/Gürgün/Documents/PythonBible/untitled/noflash.py
Traceback (most recent call last):
  File "C:/Users/G�rg�n/Documents/PythonBible/untitled/noflash.py", line 2, in <module>
    import pymem
  File "C:\Python27\lib\site-packages\pymem\__init__.py", line 7, in <module>
    import pymem.process
  File "C:\Python27\lib\site-packages\pymem\process.py", line 5, in <module>
    from win32api import GetCurrentProcess
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1

**Comment by GDman1616** [comment]
Sorry I ran it on python2 but even if I change it the error is the same

**Comment by srounet** [comment]
Did you managed to fix your issue ?

**Comment by GDman1616** [comment]
yeah its all fine now after downloading pypiwin32 as well
