### ISSUE TITLE
call remote assembly

### ISSUE THREAD

**Issue by NyshMy** [srounet/Pymem#84]
Can Python create a blank address and call remote assembly? I tried to use the createremotethread resumethread WaitForSingleObject functions and found that it took 10 calls to succeed once or twice. I don't know what the problem is. This is a very important assembly function

**Comment by LoseNine** [comment]
In fact, python remote thread injection is very simple, but generally speaking, many games require important call assembly to run in the main process of the game. If your function is very important, it is necessary for hook game main thread to call in it.

**Comment by NyshMy** [comment]
> 其实python远程线程注入很简单，但是一般来说很多游戏都需要重要的调用程序集才能运行在游戏的主线程中。如果你的函数很重要，就需要hook游戏主线程调用。

Is there any relevant code? I want to see it

**Comment by StarrFox** [comment]
you can use start_thread for this: <https://pymem.readthedocs.io/en/latest/api.html?highlight=start_thread#pymem.Pymem.start_thread>
