### ISSUE TITLE
pymem[speed] seems undocumented

### ISSUE THREAD

**Issue by divinity76** [srounet/Pymem#89]
idk what pymem[speed] is, it's not mentioned in the docs, and in the README.md it simply says
```
pip install pymem
# with speedups
pip install pymem[speed]
```
so.. what is it?

**Comment by StarrFox** [comment]
it installs the regex package which has a faster search time than the stdlib module and is used for memory scanning

This should probably be documented under the installation section, sorry about that

**Comment by StarrFox** [comment]
This has been fixed in https://github.com/srounet/Pymem/commit/3d7e10403ffe7f33a4d7c5ca031172ad838bfb05
