### ISSUE TITLE
use pyproject.toml

### ISSUE THREAD

**Issue by StarrFox** [srounet/Pymem#91]
I think switching to https://python-poetry.org/ or another pyproject.toml based solution would make development a lot faster

It allows for easier management of virtual environments and ensuring everyone is using the same packages

**Comment by StarrFox** [comment]
some other notable options are [hatch](https://github.com/pypa/hatch) and [pdm](https://github.com/pdm-project/pdm)

**Comment by v01d-gh** [comment]
Yeah. PDM is cool.
